### PR TITLE
commit

### PR DESCRIPTION
**Pull request by FireCubeStudios**
PLEASE LABEL THIS PR "hacktoberfest-accepted" for my hacktober :)

### CODE REVIEW

**Comment by FireCubeStudios** [comment]
tldr: switched to .net standard library, no more .net core project and added json.net and refit.

**Comment by dragonDScript** [comment]
Why would you not use .NET Core? Net core is cross platform and has the libraries needed for this project.

**Comment by FireCubeStudios** [comment]
> Why would you not use .NET Core? Net core is cross platform and has the libraries needed for this project.
.net standard is more cross platform and works with Xamarin, Tizen, full .NET desktop framework etc. infact .net core is a implementation of .net standard and is only limited to .net core

**Comment by dragonDScript** [comment]
OK. PR accepted 👍

**Pull request merged**
